### ISSUE TITLE
[QUESTION] Getting tensor error when running phi-2 on Mac metal: Error: cannot find tensor transformer.embd.wte.weight

### ISSUE THREAD

**Issue by lgemc** [huggingface/candle#1570] opened 2024-01-12 01:21 UTC
rustc version: rustc 1.75.0
candle repo current commit: 41915184bb3e530cc8184fdd8841c66df9285684
operative system version: 14.1.2 (23B92)
computer version: Mac Pro m1 

command executed: 

```bash
 cargo run --example phi --release -- --model 2 \
  --prompt "A skier slides down a frictionless slope of height 40m and length 80m. What's the skier speed at the bottom?"
```

**Comment by LaurentMazare** [comment] 2024-01-12 08:06
This was caused by a recent change in the naming conventions in the phi-2 tensors and should be fixed in #1572 .

**Comment by lgemc** [comment] 2024-01-15 22:22
confirmed, it was fixed after [#1572](https://github.com/huggingface/candle/pull/1572)

**Closed** 2024-01-15 22:22 UTC

**Comment by RangerMauve** [comment] 2024-01-23 06:47
Does this mean the candle library won't be updating to the new naming conventions? I was trying to run TheBloke's phi-2.Q4_K_S.gguf working, but I'm getting this same error.

**Comment by ivarflakstad** [comment] 2024-01-23 11:10
I think supporting new naming conventions is a very reasonable feature. Want to make an issue for that specifically?😊

**Comment by RangerMauve** [comment] 2024-01-23 15:51
@ivarflakstad I would love to but sadly I don't think I understand the file format to be able to open a coherent issue for it. Checking the various `from_gguf` methods hasn't helped me identify what the problem is. I'm also not sure where the error is even coming from in the candle codebase since doing a grep for the message isn't yielding results. 😅
