### ISSUE TITLE
 expected `__m256`, found `__m128`

### ISSUE THREAD

**Issue by evgenyigumnov** [huggingface/candle#613] opened 2023-08-27 05:06 UTC
root@C.6837846:~/candle$ cargo run --example llama
   Compiling hyper v0.14.27
   Compiling onig_sys v69.8.1
   Compiling candle-core v0.1.3 (/root/candle/candle-core)
   Compiling backtrace v0.3.69
   Compiling base64 v0.13.1
   Compiling utf8parse v0.2.1
   Compiling ipnet v2.8.0
   Compiling mime v0.3.17
   Compiling macro_rules_attribute-proc_macro v0.1.3
   Compiling typenum v1.16.0
   Compiling wide v0.7.11
   Compiling indicatif v0.17.6
   Compiling num-iter v0.1.43
   Compiling rayon-cond v0.1.0
   Compiling matrixmultiply v0.3.7
   Compiling derive_builder v0.12.0
   Compiling anstyle-parse v0.2.1
   Compiling esaxx-rs v0.1.8
   Compiling monostate v0.1.9
   Compiling png v0.17.10
   Compiling onig v6.4.0
   Compiling dirs v5.0.1
   Compiling fancy-regex v0.10.0
   Compiling spm_precompiled v0.1.4
   Compiling futures v0.3.28
   Compiling ureq v2.7.1
   Compiling rand_chacha v0.2.2
   Compiling unicode-normalization-alignments v0.1.12
   Compiling approx v0.5.1
   Compiling aho-corasick v0.7.20
   Compiling anyhow v1.0.75
   Compiling macro_rules_attribute v0.1.3
   Compiling itertools v0.9.0
error[E0308]: mismatched types
   --> candle-core/src/cpu/avx.rs:106:9
    |
101 |     unsafe fn load(mem_addr: *const f16) -> Self::Unit {
    |                                             ---------- expected `std::arch::x86_64::__m256` because of return type
...
106 |         _mm_loadu_ps(tmp.as_ptr())
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `__m256`, found `__m128`
    
    root@C.6837846:~/candle$ uname -m
x86_64

**Comment by evgenyigumnov** [comment] 2023-08-27 05:09
nvidia/cuda_12.0.1-devel-ubuntu20.04/ssh

**Comment by evgenyigumnov** [comment] 2023-08-27 05:20
root@C.6837846:~/candle$ rustc --version
rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by LaurentMazare** [comment] 2023-08-27 06:21
Thanks for reporting this issue, this seems to be caused by your cpu not supporting `f16c` and our backend never having been tested with this disabled. I just merged #614 that should hopefully fix this, please give it another go at the latest github tip and let us know how it goes.

**Comment by evgenyigumnov** [comment] 2023-08-27 07:34
checked - everything works - close the ticket - thanks

**Closed** 2023-08-27 17:54 UTC
