### ISSUE TITLE
send + sync support

### ISSUE THREAD

**Issue by jondot** [huggingface/candle#754] opened 2023-09-06 07:27 UTC
Hi, trying to wire parts of this library into a tokio-based inference engine, I'm starting to bump into types that are not Sync / thread friendly, specifically types that are using `Rc`, and I'm locked out of changing this or supporting Sync with any sync primitives that I have from a library-user's point of view.

Any idea if there's something behind it that I'm missing to support thread safety and async use cases?

**Comment by Narsil** [comment] 2023-09-06 07:43
Which type ?

Could you share a reproducible example ?

**Comment by jondot** [comment] 2023-09-06 07:55
Here:

https://github.com/huggingface/candle/blob/main/candle-nn/src/var_builder.rs#L15

luckily this is the only `Rc` usage in the repo as well.

**Comment by jondot** [comment] 2023-09-06 15:17
Thanks!
Well, sharing a bit on what I'm doing -- I'm taking the `examples` and making them into a library. For example, I specifically needed bigcode support, and so I shaped the bigcode example into a simple library with two steps:

1. building a model
2. prompt completion

Where building a model, would be async, but done once, and prompt completion is async as well, running many times during a session.
The first thing I bumped into was that the model was `mut`, but not all parts in the example were `mut`. I gave up and tried to whole-sale just load the files, the varbuilder and hopefully build a new pipeline every time completion was requested -- which is where I got stuck with `Rc`.

There's a ton of value in the examples, I hope it by itself becomes a library. For that to happen there probably needs to be a deliberate thinking about what's `mut` and what's not, and to separate the two types of abstractions

**Comment by LaurentMazare** [comment] 2023-09-06 20:53
Just to mention that the `mut` here is required because of the kv cache and the same applies to a bunch of transformers based models. Other models usually don't have this.
And yes it would be great to have the models moved from the examples directory to a lib, similar to the python transformers lib, that's the goal of `candle-transformers` but we first want to sketch a bunch of different examples so as to get a better sense of how we should architecture this lib.

**Comment by LaurentMazare** [comment] 2023-09-10 11:51
Closing this for now, feel free to re-open if you have further questions or open a new issue. Note that we've started moving models to `candle-transformers` so hopefully the examples will be easier to re-use.

**Closed by LaurentMazare** 2023-09-10 11:51 UTC

**Comment by jondot** [comment] 2023-09-10 18:20
amazing, thanks!
