### ISSUE TITLE
[Error] DeviceMismatchBinaryOp - mixtral quantized on cuda

### ISSUE THREAD

**Issue by edesalve** [huggingface/candle#1815] opened 2024-03-08 07:04 UTC
Hi all. The error arises during MoE forward operation in particular:

```rust

let router_logits = feed_forward_gate_inp.forward(&xs)?

```

The problem lies when the dtype of `feed_forward_gate_inp` is f16 (TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF) or f32. When instantiating `QMatMul`:

```rust

pub fn from_arc(qtensor: std::sync::Arc<QTensor>) -> Result<Self> {
    let dequantize = match qtensor.dtype() {
        GgmlDType::F32 | GgmlDType::F16 => true,
        _ => DEQUANTIZE_ALL.with(|b| *b),
    };
    let t = if dequantize {
        let tensor = qtensor.dequantize(&Device::Cpu)?;
        Self::Tensor(tensor)
    } else {
        Self::QTensor(qtensor)
    };
    Ok(t)
}

```
the tensor is placed on Cpu instead of the actual device, therefore the following `matmul` operation fails during the `same_device` check.

Modifying:

```rust

let tensor = qtensor.dequantize(&Device::Cpu)?;

```

to:

```rust

let tensor = qtensor.dequantize(&qtensor.device())?;

```

solves the issue.

**Comment by LaurentMazare** [comment] 2024-03-08 22:12
Thanks for reporting the issue and finding the root cause of it! This piece of code was from the era where quantized models were only supported on CPU and it was indeed a bug not to adapt it in the way you mentioned, your change has been merged as #1823 .

**Closed** 2024-03-27 06:04 UTC
