### ISSUE TITLE
point argument didn't handle properly in example:candle-segment-anything

### ISSUE THREAD

**Issue by lichin-lin** [huggingface/candle#989] opened 2023-09-28 21:49 UTC
@LaurentMazare, thank you for updating the script to support multi-point segmentation. However, I have discovered that the segmentation results are not as expected:

**tl;dr: Only the `first` `--point` argument is being handled; all subsequent `--point` arguments are being ignored.**

## Steps to Reproduce

```
// [0.6,0.6], [0.6, 0.55] two points on one leg
cargo run --example segment-anything --release -- --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny --point 0.6,0.6 --point 0.6,0.55 
```
![single-post-case1](https://github.com/huggingface/candle/assets/10290616/c21ad4f4-fb02-4e5e-a636-8e385b32ccc2)

```
// [0.6,0.6] single point on one leg
cargo run --example segment-anything --release -- --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny --point 0.6,0.6
```
![two-point](https://github.com/huggingface/candle/assets/10290616/0cd97468-1ec7-4d9d-8f95-34005440d701)

as you can see, we got the same result, Now, let's add a third point:

```
// [0.6,0.6], [0.6, 0.55], [0.65, 0.65] three points on one leg and the bike
cargo run --example segment-anything --release -- --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny --point 0.6,0.6 --point 0.6,0.55 --point 0.65,0.65
```
![three-point](https://github.com/huggingface/candle/assets/10290616/31d31f8f-02f4-4785-bae8-ef80cc8e83ea)

Surprisingly, we still get the same segmentation as the previous result (which is not the expected outcome). Now, let's remove the points on the leg:

```
// [0.65, 0.65] single points on the bike
cargo run --example segment-anything --release -- --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny --point 0.65,0.65
```
![single-post-case2](https://github.com/huggingface/candle/assets/10290616/10a66ec1-c15f-443a-9b92-78fc3ad3b03d)

This time, we get a different segmentation result (only the bike is segmented). For the final step, let's append the two points back to the command:

```
// [0.65, 0.65], [0.6,0.6], [0.6, 0.55] three points on the bike and the leg
cargo run --example segment-anything --release -- --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny --point 0.65,0.65 --point 0.6,0.6 --point 0.6,0.55
```
![three-point-case2](https://github.com/huggingface/candle/assets/10290616/c01d853a-79a6-487f-a560-f46b9550ba51)

As you can see, swapping the order of the points produces a different outcome.

Is there something to do with the function in the `transformer.rs` file?

**Comment by LaurentMazare** [comment] 2023-09-29 12:34
Thanks for reporting this issue, I agree that it doesn't seem to work as expected.
@GeauxEric actually enabled support for this in #945 , @GeauxEric do you want to take a look at this? No worry if you can't, I will have a look if that's the case (and it's pretty likely that the bug is somewhere in the model code that I wrote originally anyway)

**Comment by LaurentMazare** [comment] 2023-09-29 20:31
I think this was a mess up with the batch dimension and the dimension that is supposed to hold the number of points, this would well explain why only the first point ended up being used. I've pushed a fix in #998, with it I get the following mask on your multiple point example which looks a lot better.
I'll merge the changes once the CI passes, thanks again for reporting the issue and let us know if you see any more weird behaviors.
![image](https://github.com/huggingface/candle/assets/1041292/844cbecd-8525-4de8-a9d3-4198f442e514)

**Comment by lichin-lin** [comment] 2023-09-29 20:38
thank you for the fix!! @LaurentMazare 🙌 I'll test more later.
and thanks to @radames as well, your web demo is really good! 😄

**Comment by GeauxEric** [comment] 2023-09-29 23:05
Thanks to @lichin-lin for reporting the issue and @LaurentMazare for fixing it.

I double check against meta's [implementation](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/predictor.py#L186C10-L188C30)  and confirmed that the dim-0 is the batch size and dim-1 is the number of prompt points. In the candle-example, batch size is always 1.

So how come I accidentally produced the seemingly right segmentation results with my PR.
I rolled back to  a36d88325492c5e721b2045b2988cc11ef44fc0e, and ran while printing the IoU values and low_res_masks
```
cargo run --features cuda --example segment-anything  -- --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny --point 0.6,0.6 --point 0.6,0.55

low_res_mask:...
Tensor[[2, 1, 256, 256], f32, cuda:0]

iou_predictions: [[0.4907],
 [0.7242]]
```

```
cargo run --features cuda --example segment-anything  -- --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny --point 0.6,0.55

low_res_mask:...
Tensor[[1, 1, 256, 256], f32, cuda:0]

iou_predictions: [[0.7242]]
```
and due to [this line](https://github.com/huggingface/candle/blob/d188d6a7642c470732f740e93c035fd792c9706c/candle-transformers/src/models/segment_anything/sam.rs#L148), it only outputs the 1st upsampled mask even `low_res_mask`  dim-0 is greater than 1. Due to this compound effect, only the mask of the first prompt point is finally output.

**Comment by radames** [comment] 2023-09-30 03:09
thanks @LaurentMazare , I'll add the extra points UX to the web demo

**Comment by LaurentMazare** [comment] 2023-09-30 05:17
I've also just added support for negative prompts in #1000. These additional points are required _not_ to be part of the mask. They are represented as a green dot as part of the command line example and specified with `--neg-point`. E.g. without the negative point:

```bash
cargo run --example segment-anything --release -- \
    --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny \
    --point 0.5,0.65 --point 0.75,0.65
```
![image](https://github.com/huggingface/candle/assets/1041292/f5918f35-91ab-47fe-85c7-212bbe7fec50)

With an additional negative point.

```bash
cargo run --example segment-anything --release -- \
    --image candle-examples/examples/yolo-v8/assets/bike.jpg --use-tiny \
    --point 0.5,0.65 --point 0.75,0.65 --neg-point 0.1,0.65
```

![image](https://github.com/huggingface/candle/assets/1041292/7cdc03f6-1249-40c6-a7bf-70eddc59626b)

**Comment by lichin-lin** [comment] 2023-09-30 08:37
it worksing!✨ I've made a small changes to the demo site, feel free to modify the code (I'm new to Rust)

https://github.com/huggingface/candle/assets/10290616/481fe3ad-a9a4-4195-9597-f2c6088942ea

**Closed** 2023-10-02 14:43 UTC
