### ISSUE TITLE
Pth file support is broken on Windows

### ISSUE THREAD

**Issue by Nikaidou-Shinku** [huggingface/candle#1454] opened 2023-12-17 21:57 UTC
## Description

Pth file support on Windows is broken due to some issues with handling path in zip files.

## Details

When reading `tensor_infos`, `PathBuf::push` will use `\` as path separator on Windows.

https://github.com/huggingface/candle/blob/94817dac56f3c91235ad94b7b3419ab8c2e87134/candle-core/src/pickle.rs#L231

But soon `ZipArchive::by_name` may need a path with `/` as separator.

https://github.com/huggingface/candle/blob/94817dac56f3c91235ad94b7b3419ab8c2e87134/candle-core/src/pickle.rs#L713

This results in a `ZipError::FileNotFound` being raised.

---

I don't have an elegant way to solve this problem, as the separator used by path inside the zip seems to be dependent on the platform it was created on.

If anyone has a good idea, I can submit a PR for it.

**Comment by antimora** [comment] 2024-01-22 20:20
Burn project has started using Candle pickle and I can confirm CI fails on Windows (Mac and Windows work). 

I am attaching `pt` file for testing. I cannot debug it fully because my computer is Mac.

[mnist.pt.zip](https://github.com/huggingface/candle/files/14015029/mnist.pt.zip)

**Comment by klapaukh** [comment] 2024-02-28 05:49
This is fixed for me now in v0.4.0. @antimora / @Nikaidou-Shinku is it working for you too now?

**Comment by laggui** [comment] 2024-02-29 14:38
Can't speak for the specific use case previously mentioned here but our [simple example](https://burn.dev/book/import/pytorch-model.html) and all CI tests work on windows (previously disabled) with the latest release.

Thanks guys!

**Comment by antimora** [comment] 2024-02-29 17:23
> This is fixed for me now in v0.4.0. @antimora / @Nikaidou-Shinku is it working for you too now?

I will test it out and see if the bug is fixed. Thank you!

**Comment by antimora** [comment] 2024-03-02 20:36
I has been fixed, it's converted by our CI job. You may close it if you'd like, @LaurentMazare

**Closed** 2024-03-02 20:42 UTC
